🔧 chore(preview-apps.yml): remove unused setup-environment step to simplify workflow 🔧 chore(preview-apps.yml): move setup-environment step after checkout to ensure correct environment setup 🔧 chore(preview-apps.yml): fix cache key for Vercel CLI to ensure correct caching 🔧 chore(preview-apps.yml): fix environment variable name for build required status to ensure correct value is used in deployment step ✨ feat(preview-apps.yml): add support for caching build required status for each app to optimize deployment process ✨ feat(preview-apps.yml): add environment variable for build required status to deployment step to ensure correct deployment based on build status

diff --git a/.github/workflows/preview-apps.yml b/.github/workflows/preview-apps.yml
--- a/.github/workflows/preview-apps.yml
+++ b/.github/workflows/preview-apps.yml
@@ -15,9 +15,6 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up environment and cache dependencies
-        uses: sebpalluel/ci/.github/actions/setup-environment@latest
-
       - name: Get PR sha
         id: get_pull_request_sha
         run: |
@@ -74,7 +71,10 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-
+      
+      - name: Set up environment and cache dependencies
+        uses: sebpalluel/ci/.github/actions/setup-environment@latest
+  
       - name: Cache Vercel CLI
         uses: actions/cache@v2
         id: cache-vercel
@@ -93,12 +93,14 @@ jobs:
         id: app_check_build
         run: |
           npx --y nx-ignore ${{ matrix.app }}
-          echo "build_required=$?" >> $GITHUB_ENV
-  
+          echo "BUILD_REQUIRED_${{ matrix.app }}=$?" >> $GITHUB_ENV
+        
       - name: Deploy Preview to Vercel
         id: deploy_vercel
+        env:
+          BUILD_REQUIRED: ${{ env[format('BUILD_REQUIRED_{0}', matrix.app)] }}
         run: |
-          if [[ $build_required == '1' ]]; then
+          if [[ $BUILD_REQUIRED == '1' ]]; then
             cd apps/${{ matrix.app }} && vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
             # TODO remove this when Hasura correctly deployed, was temporary to fix missing env issue
             echo HASURA_GRAPHQL_ENDPOINT=https://www.hasura.staging.offline.live/ >> .env
