🐛 fix(staging-apps.yml): fix conditional check for app build requirement and deployment

diff --git a/.github/workflows/staging-apps.yml b/.github/workflows/staging-apps.yml
--- a/.github/workflows/staging-apps.yml
+++ b/.github/workflows/staging-apps.yml
@@ -42,13 +42,12 @@ jobs:
         id: app_check_build
         run: |
           npx --y nx-ignore ${{ matrix.app }}
-          echo "::set-output name=build_required::$?"
+          echo "build_required_${{ matrix.app }}=$?" >> "$GITHUB_ENV"
 
       - name: App // Vercel Environment Information
-        if: fromJson(steps.app_check_build.outputs)['build_required_${{ matrix.app }}'] === '1'
+        if: env.branch_required_${{matrix.app}} === '1'
         run: cd apps/${{ matrix.app }} && vercel pull --yes --environment=preview --git-branch=staging --token=${{ secrets.VERCEL_TOKEN }}
 
       - name: App // Deploy Staging to Vercel
-        if: fromJson(steps.app_check_build.outputs)['build_required_${{ matrix.app }}'] === '1'
-        id: app_deploy_vercel
+        if: env.branch_required_${{matrix.app}} === '1'
         run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
